# Generated by Django 3.1 on 2020-09-19 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0015_auto_20200913_1443'),
        ('authApp', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.cart')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapper.product')),
            ],
        ),
    ]
