# Generated by Django 3.1 on 2020-09-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0006_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('Shopping Cart', 'Shopping Cart'), ('wishList', 'wishList')], max_length=20),
        ),
    ]
