# Generated by Django 3.1 on 2020-09-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0007_auto_20200919_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='each_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
