# Generated by Django 3.1 on 2020-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_auto_20200919_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
