# Generated by Django 3.1 on 2020-09-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_auto_20200922_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
