# Generated by Django 3.1 on 2020-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_remove_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1234567898, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
