# Generated by Django 3.1 on 2020-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('rating', models.CharField(default='', max_length=3)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='NA', max_length=10)),
            ],
        ),
    ]
