# Generated by Django 3.1 on 2020-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_auto_20200905_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flipkart_link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
