# Generated by Django 3.1 on 2020-09-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_auto_20200912_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
    ]
