# Generated by Django 3.1 on 2020-09-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_auto_20200912_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_address',
            new_name='review_given_when',
        ),
    ]
