# Generated by Django 3.1 on 2020-09-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0012_auto_20200912_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkart_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='scrapper.product'),
        ),
    ]
