# Generated by Django 3.1 on 2020-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0013_auto_20200913_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_price',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flipkart_price',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
